export default [
  {
    title: '测试计划',
    type: 'view',
    name: Symbol('test-plans-list'),
    route: '/testplans/list',
    filePath: 'view/testPlans/index.vue',
    inNav: true,
    icon: 'iconfont icon-iconset0103',
    order: 3,
  },
  {
    title: '创建计划',
    type: 'view',
    name: Symbol('test-plans-create'),
    activePath: '/testplans/list',
    route: '/testplans/create',
    filePath: 'view/testPlans/create.vue',
    inNav: false,
    icon: 'iconfont icon-iconset0103',
    order: 3,
  },
  {
    title: '编辑计划',
    type: 'view',
    name: Symbol('test-plans-edit'),
    activePath: '/testplans/list',
    route: '/testplans/edit',
    filePath: 'view/testPlans/create.vue',
    inNav: false,
    icon: 'iconfont icon-iconset0103',
    order: 3,
  },
]